// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ This wrapper is what was missing */}
        <div className="flex h-screen overflow-hidden">
          {/* Sidebar scrolls independently */}
          <Sidebar />

          {/* Page content scrolls independently */}
          <main className="flex-1 overflow-y-auto p-8 bg-zinc-50 dark:bg-black">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
