/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/Dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UseMangmentIndexRouteImport } from './routes/useMangment/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as DashboardIndexRouteImport } from './routes/Dashboard/index'
import { Route as SkillsNewRouteImport } from './routes/skills/new'
import { Route as SkillsSkillIdRouteImport } from './routes/skills/$skillId'
import { Route as PortalModuleRouteImport } from './routes/portal/$module'
import { Route as DashboardSkillsRouteImport } from './routes/Dashboard/skills'
import { Route as DashboardSettingsRouteImport } from './routes/Dashboard/settings'
import { Route as DashboardUsersIndexRouteImport } from './routes/Dashboard/users/index'
import { Route as UsersUsernameSkillsSkillIdRouteImport } from './routes/users/$username/skills/$skillId'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseMangmentIndexRoute = UseMangmentIndexRouteImport.update({
  id: '/useMangment/',
  path: '/useMangment/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const SkillsNewRoute = SkillsNewRouteImport.update({
  id: '/skills/new',
  path: '/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillIdRoute = SkillsSkillIdRouteImport.update({
  id: '/skills/$skillId',
  path: '/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalModuleRoute = PortalModuleRouteImport.update({
  id: '/portal/$module',
  path: '/portal/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSkillsRoute = DashboardSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const UsersUsernameSkillsSkillIdRoute =
  UsersUsernameSkillsSkillIdRouteImport.update({
    id: '/users/$username/skills/$skillId',
    path: '/users/$username/skills/$skillId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/Dashboard/settings': typeof DashboardSettingsRoute
  '/Dashboard/skills': typeof DashboardSkillsRoute
  '/portal/$module': typeof PortalModuleRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/Dashboard/': typeof DashboardIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/useMangment/': typeof UseMangmentIndexRoute
  '/Dashboard/users/': typeof DashboardUsersIndexRoute
  '/users/$username/skills/$skillId': typeof UsersUsernameSkillsSkillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/Dashboard/settings': typeof DashboardSettingsRoute
  '/Dashboard/skills': typeof DashboardSkillsRoute
  '/portal/$module': typeof PortalModuleRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/Dashboard': typeof DashboardIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/useMangment': typeof UseMangmentIndexRoute
  '/Dashboard/users': typeof DashboardUsersIndexRoute
  '/users/$username/skills/$skillId': typeof UsersUsernameSkillsSkillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/Dashboard/settings': typeof DashboardSettingsRoute
  '/Dashboard/skills': typeof DashboardSkillsRoute
  '/portal/$module': typeof PortalModuleRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/Dashboard/': typeof DashboardIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/useMangment/': typeof UseMangmentIndexRoute
  '/Dashboard/users/': typeof DashboardUsersIndexRoute
  '/users/$username/skills/$skillId': typeof UsersUsernameSkillsSkillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Dashboard'
    | '/about'
    | '/contact'
    | '/Dashboard/settings'
    | '/Dashboard/skills'
    | '/portal/$module'
    | '/skills/$skillId'
    | '/skills/new'
    | '/Dashboard/'
    | '/skills/'
    | '/useMangment/'
    | '/Dashboard/users/'
    | '/users/$username/skills/$skillId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/Dashboard/settings'
    | '/Dashboard/skills'
    | '/portal/$module'
    | '/skills/$skillId'
    | '/skills/new'
    | '/Dashboard'
    | '/skills'
    | '/useMangment'
    | '/Dashboard/users'
    | '/users/$username/skills/$skillId'
  id:
    | '__root__'
    | '/'
    | '/Dashboard'
    | '/about'
    | '/contact'
    | '/Dashboard/settings'
    | '/Dashboard/skills'
    | '/portal/$module'
    | '/skills/$skillId'
    | '/skills/new'
    | '/Dashboard/'
    | '/skills/'
    | '/useMangment/'
    | '/Dashboard/users/'
    | '/users/$username/skills/$skillId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PortalModuleRoute: typeof PortalModuleRoute
  SkillsSkillIdRoute: typeof SkillsSkillIdRoute
  SkillsNewRoute: typeof SkillsNewRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  UseMangmentIndexRoute: typeof UseMangmentIndexRoute
  UsersUsernameSkillsSkillIdRoute: typeof UsersUsernameSkillsSkillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard': {
      id: '/Dashboard'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useMangment/': {
      id: '/useMangment/'
      path: '/useMangment'
      fullPath: '/useMangment/'
      preLoaderRoute: typeof UseMangmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/': {
      id: '/Dashboard/'
      path: '/'
      fullPath: '/Dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/skills/new': {
      id: '/skills/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof SkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillId': {
      id: '/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof SkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$module': {
      id: '/portal/$module'
      path: '/portal/$module'
      fullPath: '/portal/$module'
      preLoaderRoute: typeof PortalModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/skills': {
      id: '/Dashboard/skills'
      path: '/skills'
      fullPath: '/Dashboard/skills'
      preLoaderRoute: typeof DashboardSkillsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/Dashboard/settings': {
      id: '/Dashboard/settings'
      path: '/settings'
      fullPath: '/Dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/Dashboard/users/': {
      id: '/Dashboard/users/'
      path: '/users'
      fullPath: '/Dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/users/$username/skills/$skillId': {
      id: '/users/$username/skills/$skillId'
      path: '/users/$username/skills/$skillId'
      fullPath: '/users/$username/skills/$skillId'
      preLoaderRoute: typeof UsersUsernameSkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSkillsRoute: typeof DashboardSkillsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSkillsRoute: DashboardSkillsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PortalModuleRoute: PortalModuleRoute,
  SkillsSkillIdRoute: SkillsSkillIdRoute,
  SkillsNewRoute: SkillsNewRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  UseMangmentIndexRoute: UseMangmentIndexRoute,
  UsersUsernameSkillsSkillIdRoute: UsersUsernameSkillsSkillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
