//"use client"; for clint side or some react function
import Navbar from './Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
//by default in next all components in sec/app folder are react server components mean server side rendering
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      
      <Navbar/>
    </html>
  )
}
{/*layout.js remain save every where*/}